audio:
    format:
        sample-rate: 8000
        sample-size-in-bits: 16
        channels: 1
        signed: true
        big-endien: true
        buffer-size: 2048
    processing:
        frame-length: 25
        frame-step: 10
        pre-emphasis: 0.97